# -*- coding: utf-8 -*-
"""proj3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxwPzsgTxJRmuh2-EewUozZm0m3I0A8g
"""

def add_employees():
  emp={"name":input("Enter the name: "),"department":input("Enter the department"),"score":int(input("Enter the score: "))}
  save_employee(emp)
def load_employees():
  with open("Employees.txt","r") as file:
      dat=file.read()
      lines=dat.split("\n")
  emp=[]
  for line in lines:
    if line=="":
      continue
    dic=line.split(",")
    newdict={"name":dic[0],"department":dic[1],"score":int(dic[2])}
    emp.append(newdict)
  return emp
def save_employee(emp):
  with open("Employees.txt","a")as file:
        file.write(f"{emp['name']},{emp['department']},{emp['score']}\n")
def view_employees():
  emp=load_employees()
  print("The EMployees are:")
  for e in emp:
    print(f"{e['name']},{e['department']},{e['score']}")
def search_employee():
  emp=input("Enter the name of employee to search: ")
  found=False
  dat=load_employees()
  for line in dat:
      if emp in line["name"]:
        print(f"{line['name']},{line['department']},{line['score']}")
        found=True
  if not found:
    print("EMployee Not found")
def calculate_average():
  dat=load_employees()
  avg=0
  for line in dat:
    avg+=line['score']
  avg/=len(dat)
  print("Average of Employees:",avg)
def find_grade(score):
  if score<0:
    return "Invalid"
  elif score<=59:
    return "Poor"
  elif score<=74:
    return "Average"
  elif score<=89:
    return "Good"
  elif score<=100:
    return "Excellent"
  else :
    return "Invalid"
def performance_report():
  dat=load_employees()
  for line in dat:
    print(f"{line['name']} |{line['score']} | {find_grade(line['score'])}")

while True:
  print("===== EMPLOYEE DATA MANAGEMENT =====\n\n1. View Employees\n2. Add Employee\n3. Search Employee\n4. Calculate Average Score\n5. Generate Performance Report\n6. Exit\n")
  choice=int(input("Enter your choice:"))
  if choice==1:
    view_employees()
  elif choice==2:
    add_employees()
  elif choice==3:
    search_employee()
  elif choice==4:
    calculate_average()
  elif choice==5:
    performance_report()
  elif choice==6:
    break
  else :
    print("Invalid choice")
